### ISSUE TITLE
Y not add "apt-get" package ?


### ISSUE THREAD

**Issue by mrHola21** [luksi-l/console_command#1]

**Comment by robtech21** [comment]
Well... Considering how broken the code is, I don't think there will ever be any useful features. However, you can check out my [Digital Swiss Army Knife](https://github.com/robtech21/DigitalSwissArmyKnife) for a decent Python multitool.

**Comment by mrHola21** [comment]
@robtech21  i seriouly liked ur project

**Comment by luksi-l** [comment]
I will add that command...right now i have a small problem

**Comment by mrHola21** [comment]
And what's that ?

**Comment by robtech21** [comment]
> @robtech21 i seriouly liked ur project

@mrHola21 Thanks. I've got a new update for it in the works but I'm quite busy with general life stuff so I don't think it'll be out anytime soon.
