### ISSUE TITLE
oh lord

### ISSUE THREAD

**Issue by HBPlayz** [luksi-l/console_command#4]
what the hell is this code

**Comment by B00bleaTea** [comment]
AAAAAAAAAAAAAAAAAAAAAAAAA

**Comment by AcaiBerii** [comment]
bbbbbbbbhbhbhbhb k 8iuu kkkkkkkkkk ggh

**Comment by robtech21** [comment]
> what the hell is this code

I thought the same thing when I [forked it](https://github.com/robtech21/terminalPy) and saw that the author didn't just use a `while True:` loop but instead copy pasted the same code so many times.

**Comment by mrHola21** [comment]
i agree thats bad

**Comment by AcaiBerii** [comment]
b h khkjmdm eeh
